[package]
name = "netparser"
version = "0.1.0"
authors = ["Mark Pedersen markrepedersen@gmail.com"]
edition = "2018"
description = "Binary application for sniffing network packets."

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
netparse = { path = "../../lib/netparse" }
tui = "0.9"
termion = "1.5"
pcap = "0.7.0"
crossbeam = "0.7"